AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  Lambda:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./lambda
    Properties:
      Architectures:
      - x86_64
      Environment:
        Variables:
          SECRET_ARN: !Ref Secret
          PINECONE_INDEX_NAME: line-bot-openai
      Events:
        WebHook:
          Type: Api
          Properties:
            Path: /post
            Method: post
      MemorySize: 256
      PackageType: Image
      Policies:
      - arn:aws:iam::aws:policy/SecretsManagerReadWrite
      Timeout: 16

  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      SecretString: "{\"CHANNEL_ACCESS_TOKEN\":\"line\",\"CHANNEL_SECRET\":\"line\",\"OPENAI_API_KEY\":\"openai\",\"PINECONE_API_KEY\":\"pinecone\"}"

Outputs:
  LambdaApi:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/post/"
