AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  Lambda:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./lambda
    Properties:
      Architectures:
      - x86_64
      Environment:
        Variables:
          SECRET_ARN: !Ref Secret
      Events:
        WebHook:
          Type: Api
          Properties:
            Path: /post
            Method: post
      PackageType: Image
      Policies:
      - arn:aws:iam::aws:policy/SecretsManagerReadWrite

  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      SecretString: "{\"CHANNEL_ACCESS_TOKEN\":\"placeholder\",\"CHANNEL_SECRET\":\"placeholder\"}"

Outputs:
  LambdaApi:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/post/"
